// <auto-generated />
using Assignment4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment4.Migrations
{
    [DbContext(typeof(Assignment4DbContext))]
    partial class Assignment4DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment4.Models.FuelCalcItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountOfFuel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostOfFuel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EndOdometer")
                        .HasColumnType("int");

                    b.Property<int>("StartOdometer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FuelCalcItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfFuel = 50m,
                            CostOfFuel = 25.5m,
                            EndOdometer = 100,
                            StartOdometer = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
